name: wc_dart_framework_generator
description: Code generator for wc_dart_framework
version: 1.12.2
homepage: https://github.com/aarajput/wc_framework/tree/main/wc_dart_framework_generator
repository: https://github.com/aarajput/wc_framework
issue_tracker: https://github.com/aarajput/wc_framework/issues
documentation: https://github.com/aarajput/wc_framework/blob/main/wc_dart_framework/README.md

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  source_gen: ">=3.0.0 <5.0.0"
  analyzer: ">=7.5.9 <9.0.0"
  # analyzer: 7.5.9
  build: ">=3.0.0 <5.0.0"
  change_case: ^2.0.0
  path: ^1.8.2
  glob: ^2.0.1
  wc_dart_framework: ^1.11.0
  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^6.0.0
